### ISSUE TITLE
Get-UnattendedInstallFiles looking for incorrect filename

### ISSUE THREAD

**Issue by ImAnEnabler** [PowerShellEmpire/PowerTools#53]
Get-UnattendedInstallFiles is looking for unattended.xml, but Microsoft documentation says this should be unattend.xml

https://technet.microsoft.com/en-us/library/cc749415(WS.10).aspx

**Comment by leechristensen** [comment]
FWIW, I've got an open pull request that just checks for both (as well as other missing unattend.xml locations)

**Comment by HarmJ0y** [comment]
Merged now, should be good. Apologies for the delay :)
