### ISSUE TITLE
Get-GptTmpl non domain joined User/PC

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellEmpire/PowerTools#57]
Using `runas /netonly` technique, for some reason Test-Path returns false unless you have the drive mapped?

e.g. net use * \\target.com

Then Test-Path will start returning true...

**Comment by HarmJ0y** [comment]
Hrmmm. What do you think about a -MapDrives argument to anything that uses remote Test-Path's, something like "New-PSDrive –Name $RandName –PSProvider FileSystem –Root “\\SERVER\share” . Could also supply alternate credentials.

**Comment by HarmJ0y** [comment]
The version_2.0 branch just got a push to hopefully support this- Get-GptTmpl, Get-GroupsXML, Get-NetGPOGroup, Find-GPOComputerAdmin, Find-GPOLocation and Get-DomainPolicy just got a "-UsePSDrive" switch that should automate the creation of a randomized session-only PSDrive for the mounting of locations to search for policy files. Let me know if this does/doesn't work, and I'll close the issue when it's a confirmed fix.

Also, Find-InterestingFile and Invoke-FileFinder received the flag as well, along with a -Credential option to specify alternate credentials for filesearching. Again, minimally tested, so let me know what breaks :)

**Comment by HarmJ0y** [comment]
The version_2.0 branch just got a push to hopefully support this- Get-GptTmpl, Get-GroupsXML, Get-NetGPOGroup, Find-GPOComputerAdmin, Find-GPOLocation and Get-DomainPolicy just got a "-UsePSDrive" switch that should automate the creation of a randomized session-only PSDrive for the mounting of locations to search for policy files. Let me know if this does/doesn't work, and I'll close the issue when it's a confirmed fix.

Also, Find-InterestingFile and Invoke-FileFinder received the flag as well, along with a -Credential option to specify alternate credentials for file searching. Again, minimally tested, so let me know what breaks :)
