### ISSUE TITLE
PageSize set in individual functions

### ISSUE THREAD

**Issue by Meatballs1** [PowerShellEmpire/PowerTools#59]
Without setting $searcher.PageSize we limit results to 1000 default, so ideally we always want to set a PageSize, and ideally this should all be refactored into the Get-DomainSearcher method? Additionally it may be worthwhile having it as customizable - so different page sizes can be specified :)

**Comment by HarmJ0y** [comment]
You are correct (as usual) :) 

Working on the code now, should have it up in a branch shortly.

**Comment by HarmJ0y** [comment]
I think this should do it, look correct?  https://github.com/PowerShellEmpire/PowerTools/commit/9a95acc43aea0a35f6976b68720b1c111e2d2784
